### ISSUE TITLE
It doesn't work on firefox 26

### ISSUE THREAD

**Issue by brucmao** [albancrommer/skiptco#1] opened 2013-12-15 17:15 UTC
It doesn't work on firefox 26,please check it

**Comment by albancrommer** [comment] 2016-09-28 20:18
Sorry missed the issue...

Yes, that is possible. the plugin should be reworked for FF so that it might be compliant with tweetdeck.

**Comment by rugk** [comment] 2016-09-28 20:53
Haha, you reply to this issue _now_?

I mean I can confirm it works with FF 49.0.1, but I have no plans to test it with FF 26. :laughing:

**Comment by albancrommer** [comment] 2016-10-02 19:45
Well, since it keeps working in FF, we'll close the issue. Checked in FF 49 and twitter.

**Closed as completed by albancrommer** 2016-10-02 19:45 UTC
